import re
from collections import OrderedDict
from lambda_function import split_string

def build_test_data(raw_text):
    words_list = split_string(raw_text)
    pnum_map = OrderedDict()
    word_index_map = OrderedDict()
    par_num = -1
    cursor = 0
    for index, word in enumerate(words_list):
        if re.match(r'^\d+$', word):
            par_num = int(word)
            pnum_map[par_num] = index
        pos = raw_text[cursor:].index(word)
        word_index_map[index] = pos + cursor
        cursor += pos + len(word)

    pnum_map[par_num+1] = len(words_list)
    word_index_map[len(words_list)] = len(raw_text)

    return {
        'raw_text': raw_text,
        'words_list': words_list,
        'pnum_map': pnum_map,
        'word_index_map': word_index_map
    }

SIMPLE_TEST = {
    'quote': 'quote test',
    'english_text': '1 this is a simple quote test 2 end',
    'spanish_text': '1 esta es una prueba de cotización simple 2 fin',
    'expected': {
        'quote': 'quote test ', 
        'translation': 'una prueba de cotización simple ', 
        'paragraphNumber': 1
    }
}

FULL_PARAGRAPH = {
    'quote': 'God loves to fellowship with His creature. In the garden of Eden we are told, that when man walked in the uprightness of God, God came down in the cool of the evening and fellowshipped with His children. Then, one day there was a voice came up in the Presence of God and said, “Those Your loved ones, Your children, has fallen, and they have sinned and have did that which was wrong.” You know what…?…God didn’t just select some Angel to go down and look it over, to see if it was so or not, or a certain Cherubim of the heavens, but God came Hisself, crying, “Adam, where art Thou?” God, Himself, come crying for His lost child. When He found Him hiding in the bushes, behind sewed fig leaves, He said, “Who told you you were naked?” And he could not come out and have fellowship no more with God.',
    'english_text': '[Blank.spot.on.tape] Man...\n9 God loves to fellowship with His creature. In the garden of Eden we are told, that when man walked in the uprightness of God, God came down in the cool of the evening and fellowshipped with His children. Then, one day there was a voice came up in the Presence of God and said, “Those Your loved ones, Your children, has fallen, and they have sinned and have did that which was wrong.” You know what...?... God didn\'t just select some Angel to go down and look it over, to see if it was so or not, or a certain Cherubim of the heavens, but God came Hisself, crying, “Adam, where art Thou?” God, Himself, come crying for His lost child.\nWhen He found Him hiding in the bushes, behind sewed fig leaves, He said, “Who told you you were naked?” And he could not come out and have fellowship no more with God. 10 Now, if there is a true fellowship... And God is love, and love demands a fellowship, like the young couple. When the boy meets the girl, and he says to her... He thinks she\'s so pretty, and—and she\'s fond of him, they want to have fellowship, a real fellowship. But before they can have this fellowship, there has to be an agreement. Before they can enter into wedding, wedlock, there has to an agreement for this certain fellowship. And it\'s based upon the truces or their pledges to each other, and then holy wedlock. And then we enter into a life-long fellowship. But before we can enter into that fellowship, there has to be a—an agreement first.',
    'spanish_text': '[Porción sin grabar en la cinta-Ed.].\n9 Dios ama tener compañerismo con Sus criaturas. En el huerto del Edén, se nos dijo, que cuando el hombre caminaba en la rectitud de Dios, Dios descendía en la frescura de la tarde y tenía compañerismo con Sus hijos. Luego, un día hubo una voz que subió a la Presencia de Dios, y dijo: “Esos, Tus amados, Tus hijos, han caído, y han pecado y han hecho eso, lo cual está errado”. Saben qué?, Dios no seleccionó a algún Angel para que bajara e investigara, para ver si era así o no, o a un cierto Querubín de los Cielos, sino que Dios mismo vino, clamando: “Adán, dónde estás?” Dios mismo vino clamando por Su hijo perdido.\nCuando El lo encontró escondido en los arbustos, detrás de las hojas de higuera cosidas, El dijo: “Quién te enseñó que estabas desnudo?” Y él ya no pudo salir y tener compañerismo con Dios. 10 Ahora, si hay un compañerismo verdadero... Y Dios es amor, y el amor demanda un compañerismo. Así como una pareja joven: cuando el muchacho conoce a la muchacha, y él le dice a ella... él piensa que ella es muy hermosa, y-y ella está enamorada de él; ellos quieren tener compañerismo, un verdadero compañerismo. Pero antes que ellos puedan tener este compañerismo, tiene que haber un acuerdo. Antes que puedan entrar en la boda, en matrimonio, tiene que haber un acuerdo para este cierto compañerismo. Y es basado sobre la seguridad de sus promesas hechas el uno al otro, y luego el matrimonio. Y luego entramos en un compañerismo por toda la vida. Pero antes que podamos entrar en ese compañerismo, primero tiene que haber un-un acuerdo.',
    'expected': {
        'quote': 'God loves to fellowship with His creature. In the garden of Eden we are told, that when man walked in the uprightness of God, God came down in the cool of the evening and fellowshipped with His children. Then, one day there was a voice came up in the Presence of God and said, “Those Your loved ones, Your children, has fallen, and they have sinned and have did that which was wrong.” You know what...?... God didn\'t just select some Angel to go down and look it over, to see if it was so or not, or a certain Cherubim of the heavens, but God came Hisself, crying, “Adam, where art Thou?” God, Himself, come crying for His lost child.\nWhen He found Him hiding in the bushes, behind sewed fig leaves, He said, “Who told you you were naked?” And he could not come out and have fellowship no more with God. ', 
        'translation': 'Dios ama tener compañerismo con Sus criaturas. En el huerto del Edén, se nos dijo, que cuando el hombre caminaba en la rectitud de Dios, Dios descendía en la frescura de la tarde y tenía compañerismo con Sus hijos. Luego, un día hubo una voz que subió a la Presencia de Dios, y dijo: “Esos, Tus amados, Tus hijos, han caído, y han pecado y han hecho eso, lo cual está errado”. Saben qué?, Dios no seleccionó a algún Angel para que bajara e investigara, para ver si era así o no, o a un cierto Querubín de los Cielos, sino que Dios mismo vino, clamando: “Adán, dónde estás?” Dios mismo vino clamando por Su hijo perdido.\nCuando El lo encontró escondido en los arbustos, detrás de las hojas de higuera cosidas, El dijo: “Quién te enseñó que estabas desnudo?” Y él ya no pudo salir y tener compañerismo con Dios. ', 
        'paragraphNumber': 9
    }
}

MULTI_PARAGRAPH = {
    'quote': 'Over in Ecclesiastes, the 12th chapter and the 13th verse, it’s written like this, see. Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the full duty of man. The conclusion of the whole matter is to “fear God.” And, when, you cannot have respects until you have fear. You’ve got to have fear of God. Solomon said also, in the Proverbs, that: The fear of God is the beginning of wisdom: The fear of God is the beginning of wisdom: Now, that don’t mean that you’re afraid of Him, but that means that you are giving Him “respects” and “reverence.” And when you respect God, you fear God. You fear that you might displease Him in some way, you fear lest you would do something wrong. You wouldn’t want to. I fear my mother. I fear my—my wife. I fear my church. I fear all of God’s servants, unless I should put a stumbling block somewhere in their way. I—I fear the people. I fear the people of the city, unless I should do something wrong that would cause them to think that I wasn’t a Christian. See, you’ve got, before you can have respects, you’ve got to have fear. And God demands it, He demands respects. God does, He demands it. And fear brings it. And we know that fear brings respects.',
    'english_text': '''24 I want to take a subject from there of “Respects.” Reading here, David crying out to the Lord, respect is what we owe to God. And that's one thing that I would like, to drill this to the heart of every person here tonight, that in all things that we see going on, we must give respects to it. See, we must respect it. And David said that when they were very few men of Israel, perhaps Abraham, Isaac, and Jacob, who he was speaking of, very few men, that He rebuked nations and kings for them. God rebuked the nations and kings, saying, “Touch not my anointed, and do my prophets no harm.” 25 Over in Ecclesiastes, the twelfth chapter and the thirteenth verse, it's written like this, see. Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the full duty of man. The conclusion of the whole matter is to fear God. And you cannot have respects until you have fear. You've got to have fear of God. Solomon said also, in the Proverbs, that the fear of God is the beginning of wisdom. The fear of God is the beginning of wisdom. Now, that don't mean that you're afraid of Him, but that means that you are giving Him respects and reverence. And when you respect God, you fear God. You fear that you might displease Him in some way, you fear lest you would do something wrong. You wouldn't want to. . . . 26 I fear my mother. I fear my wife. I fear my church. I fear all of God's servants, unless I should put a stumbling block somewhere in their way. I fear the people. I fear the people of the city, unless I should do something wrong that would cause them to think that I wasn't a Christian. See, you've got . . . before you can have respects, you've got to have fear. And God demands it. He demands respects. God does, He demands it. And fear brings it. And we know that fear brings respects. 27 Now, you take for instance, a man, he's a farmer or maybe he's a shop worker, and nobody pays any attention to him. But let him get a job on the police force and come down the street, and as a policeman with his badge and uniform on (where, maybe someone wouldn't speak to him the day before), “Hello, there, John! How are you?” See? Why is it? It's kind of an awe, or a fear, or a respect, because of it. Maybe he gets elected to be the mayor of the city, or maybe. . . . ''',
    'spanish_text': '''24 Quiero tomar un tema de allí, de: Respetos. Leyendo aquí, David clamando al Señor. Respetos es lo que le debemos a Dios. Y esa es una cosa que me gustaría, meter esto en el corazón de toda persona que está aquí esta noche, que, en todas las cosas que vemos que están sucediendo, debemos dar respetos a ello. Ven?, debemos respetarlo. Y David dijo que cuando ellos eran muy pocos hombres de Israel, quizás Abraham, Isaac, y Jacob, de quien él estaba hablando, muy pocos hombres, que El reprendió naciones y reyes por ellos. Dios reprendió a las naciones y a los reyes, diciendo: “No toquéis a Mis ungidos, ni hagáis mal a Mis profetas”. 25 Allá en Eclesiastés, el capítulo 12 y el versículo 13, está escrito así, ven? El fin de todo el discurso oído es este: Teme a Dios, y guarda sus mandamientos; porque esto es el total del hombre. El fin de todo el discurso es “teme a Dios”. Y, cuando, Uds. no pueden tener respetos hasta que tengan temor. Uds. tienen que tener temor de Dios. Salomón también dijo, en los Proverbios, que: El temor de Jehová es el principio de la sabiduría, El temor de Jehová es el principio de la sabiduría, Ahora, eso no quiere decir que Uds. tienen miedo de El, sino que eso significa que Uds. están dándole a El “respetos” y “reverencia”. Y cuando Uds. respetan a Dios, Uds. temen a Dios. Uds. temen de que pudieran desagradarlo en alguna manera, Uds. temen para no hacer algo errado. Uds. no quisieran. 26 Yo temo a mi madre. Yo temo a mi-mi esposa. Yo temo a mi iglesia. Yo temo a todos los siervos de Dios, no sea que yo pusiera un tropiezo en alguna parte en su camino. Yo-yo temo a la gente. Yo temo a la gente de la ciudad, no sea que yo hiciera algo errado que causara que ellos pensaran que no soy un Cristiano. Ven?, Uds. tienen, antes de que Uds. puedan tener respetos, Uds. tienen que tener temor. Y Dios lo demanda, El demanda respetos. Dios lo hace, El lo demanda. Y el temor lo trae. Y sabemos que el temor trae respetos. 27 Ahora, tomen por ejemplo, al hombre, él es un agricultor o quizás es un-un trabajador de taller, y nadie le presta atención a él. Pero dejen que él consiga un trabajo en la fuerza de policía y venga por la calle, y como-como policía con su insignia y uniforme puestos, (donde, quizás alguien no le hablaba a él el día anterior), “Hola, Juan! Cómo estás?” Ven? Por qué es? Es como un miedo, o un temor, o un respeto, debido a eso. Quizás él es elegido para ser el alcalde de la ciudad, o quizás...''',
    'expected': {
        'quote': "Over in Ecclesiastes, the twelfth chapter and the thirteenth verse, it's written like this, see. Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the full duty of man. The conclusion of the whole matter is to fear God. And you cannot have respects until you have fear. You've got to have fear of God. Solomon said also, in the Proverbs, that the fear of God is the beginning of wisdom. The fear of God is the beginning of wisdom. Now, that don't mean that you're afraid of Him, but that means that you are giving Him respects and reverence. And when you respect God, you fear God. You fear that you might displease Him in some way, you fear lest you would do something wrong. You wouldn't want to. . . . 26 I fear my mother. I fear my wife. I fear my church. I fear all of God's servants, unless I should put a stumbling block somewhere in their way. I fear the people. I fear the people of the city, unless I should do something wrong that would cause them to think that I wasn't a Christian. See, you've got . . . before you can have respects, you've got to have fear. And God demands it. He demands respects. God does, He demands it. And fear brings it. And we know that fear brings respects. ", 
        'translation': 'Allá en Eclesiastés, el capítulo 12 y el versículo 13, está escrito así, ven? El fin de todo el discurso oído es este: Teme a Dios, y guarda sus mandamientos; porque esto es el total del hombre. El fin de todo el discurso es “teme a Dios”. Y, cuando, Uds. no pueden tener respetos hasta que tengan temor. Uds. tienen que tener temor de Dios. Salomón también dijo, en los Proverbios, que: El temor de Jehová es el principio de la sabiduría, El temor de Jehová es el principio de la sabiduría, Ahora, eso no quiere decir que Uds. tienen miedo de El, sino que eso significa que Uds. están dándole a El “respetos” y “reverencia”. Y cuando Uds. respetan a Dios, Uds. temen a Dios. Uds. temen de que pudieran desagradarlo en alguna manera, Uds. temen para no hacer algo errado. Uds. no quisieran. 26 Yo temo a mi madre. Yo temo a mi-mi esposa. Yo temo a mi iglesia. Yo temo a todos los siervos de Dios, no sea que yo pusiera un tropiezo en alguna parte en su camino. Yo-yo temo a la gente. Yo temo a la gente de la ciudad, no sea que yo hiciera algo errado que causara que ellos pensaran que no soy un Cristiano. Ven?, Uds. tienen, antes de que Uds. puedan tener respetos, Uds. tienen que tener temor. Y Dios lo demanda, El demanda respetos. Dios lo hace, El lo demanda. Y el temor lo trae. Y sabemos que el temor trae respetos. ', 
        'paragraphNumber': 25
    }
}

MID_PARAGRAPH = {
    'quote': 'Bring upon us, today, Lord, that godly fear, that we might know that we are the subjects of Thy hand, and will stand some day in Thy Divine judgment. And there is only one remedy that we know of, and that Your Word teaches of, that’s the Blood of Thy Son Jesus, that makes intercessions for us, this morning, in the Presence of the Almighty, bringing us into reconciliation to Him, through His merits. And then it is given to us, unmerited grace, and we love Him for this. And as we…',
    'english_text': '''16 And now, right after the first of the year, January, I'm leaving for overseas again. I'll be in Kingston, Jamaica, at the race tracks, in January, and from there to Puerto Rico and so forth. So let us bow our heads just a moment, in prayer, to our great, loving Christ. 17 O Lord, Thou has been our refuge in every generation. Thou art a very present help in the time of trouble. And to know that Thy loving presence never does fail. It goes before us and we are taught that the angels of God are encamped about those who fear Him. Bring upon us, today, Lord, that godly fear, that we might know that we are the subjects of Thy hand, and will stand someday in Thy divine judgment. And there is only one remedy that we know of, and that Your Word teaches of, that's the blood of Thy Son, Jesus, that makes intercessions for us this morning, in the presence of the Almighty, bringing us into reconciliation to Him, through His merits. And then it is given to us, unmerited grace, and we love Him for this. And as we.... 18 In our mind lays hundreds of great things that You have done. And the greatest of all, we can think of, is when You saved us from a life of death, where in us dwelt death because of sin and trespasses. But by accepting His pardon, according to His Word.... For it is written, “He that heareth My words and believeth on Him that sent Me, has immortal life.” And we believe it and have accepted it, and witness the presence of the Holy Spirit.''',
    'spanish_text': '''16 Y ahora, inmediatamente a principios del año, yo... en enero, estaré saliendo otra vez para ultramar, para la... Será en Kingston, Jamaica, en la... en el hipódromo para... en enero, y de allí a Puerto Rico y así sucesivamente. Inclinemos nuestros rostros por un momento para orarle a nuestro gran, amoroso Cristo. 17 Oh, Señor, Tú has sido nuestro Refugio de generación en generación. Tú eres nuestro pronto auxilio en las tribulaciones. Y el saber que Tu Presencia amorosa nunca falla, va al frente de nosotros y hemos sido enseñados que los Ángeles de Dios acampan alrededor de los que le temen. Mándanos este día, Señor, ese temor reverencial, que podamos conocer que somos los súbditos de Tu mano, y que un día tendremos que pararnos en Tu juicio Divino. Y solamente hay un remedio que conocemos, y que Tu Palabra nos enseña; viene siendo la Sangre de Tu Hijo Jesús, que hace intercesión por nosotros en esta mañana en la Presencia del Todopoderoso, reconciliándonos a Él por medio de Sus méritos. Y luego se nos es dada, gracia inmerecida, y le amamos a Él por esto. Y a medida que nosotros... 18 En nuestras mentes reposan cientos de cosas que Tú has hecho. Y la cosa más grande en la que podemos pensar, es cuando Tú nos salvaste de la vida de muerte, cuando en nosotros habitaba la muerte a causa del pecado y las transgresiones. Pero al aceptar Su perdón, de acuerdo a Su Palabra... Porque escrito está: “Él que escucha Mis Palabras, y cree en el que Me ha enviado, tiene vida eterna”. Y nosotros lo creemos y lo aceptamos, y atestiguamos la Presencia del Espíritu Santo.''',
    'expected': {
        'quote': "Bring upon us, today, Lord, that godly fear, that we might know that we are the subjects of Thy hand, and will stand someday in Thy divine judgment. And there is only one remedy that we know of, and that Your Word teaches of, that's the blood of Thy Son, Jesus, that makes intercessions for us this morning, in the presence of the Almighty, bringing us into reconciliation to Him, through His merits. And then it is given to us, unmerited grace, and we love Him for this. And as we.... 18 ", 
        'translation': 'temen. Mándanos este día, Señor, ese temor reverencial, que podamos conocer que somos los súbditos de Tu mano, y que un día tendremos que pararnos en Tu juicio Divino. Y solamente hay un remedio que conocemos, y que Tu Palabra nos enseña; viene siendo la Sangre de Tu Hijo Jesús, que hace intercesión por nosotros en esta mañana en la Presencia del Todopoderoso, reconciliándonos a Él por medio de Sus méritos. Y luego se nos es dada, gracia inmerecida, y le amamos a Él por esto. Y a medida que nosotros... 18 ', 
        'paragraphNumber': 17
    }
}

